name: angular_gallery_section
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^5.10.0
  ngdart: ^8.0.0-dev.1
  ngcomponents: 
    path: ../ngcomponents
  angular_gallery:
    path: ../angular_gallery
  build: ^2.1.1
  build_config: ^1.0.0
  glob: ^2.0.2
  markdown: ^7.0.2
  mustache_template: ^2.0.0
  collection: ^1.18.0
  js: ^0.6.1
  path: ^1.6.1
  sass: '>=1.15.3 <2.0.0'
  sanitize_html: ^2.0.0
  lints: ^3.0.0