name: angular_gallery_section
publish_to: none

environment:
  sdk: '>=2.10.5 <3.0.0'

dependencies:
  analyzer: ^2.4.0
  angular: ^7.0.1
  ngcomponents: ^1.0.0
  angular_gallery:
    path: ../angular_gallery
  build: ^2.1.1
  build_config: ^1.0.0
  glob: ^2.0.2
  markdown: ^4.0.0
  mustache: ^1.0.0
  path: ^1.6.1
  sass: '>=1.15.3 <2.0.0'

dependency_overrides:
  ngcomponents:
    path: ../ngcomponents
