name: ngcomponents
version: 1.0.3
description: >
  The official Material Design components for AngularDart. Used at Google in
  production apps.
repository: https://github.com/angulardart/ngcomponents
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ngdart: ^7.1.0
  ngforms: ^4.1.0
  async: ^2.1.0
  build: ^2.1.1
  build_config: ^1.0.0
  built_collection: ^5.1.1
  change_case: ^1.0.1
  collection: ^1.15.0-nullsafety.4
  fixnum: ^1.0.0
  intl: ^0.17.0
  js: ^0.6.1
  logging: ^1.0.2
  meta: ^1.0.4
  observable: ^0.24.0
  protobuf: ^2.0.0
  quiver: ^3.0.1
  sass_builder: ^2.0.2

dev_dependencies:
  ngtest: ^4.0.1
  build_runner: ^2.2.0
  build_test: ^2.1.5
  build_web_compilers: ^3.2.4
  grinder: ^0.9.0
  lints: ^1.0.1
  path: ^1.6.1
  test: ^1.0.0
