# See https://github.com/google/mono_repo.dart for details
stages:
  - analyze_and_format_core:
    - group:
        - format
        - analyze: --fatal-infos .
      sdk:
        - beta
    - group:
        - analyze: .
      sdk:
        - 2.17.0
        - stable

cache:
  directories:
  - .dart_tool
