name: angular_gallery
publish_to: none
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ngdart: ^8.0.0-dev.1
  ngcomponents: 
    path: ../ngcomponents
  ngforms: ^5.0.0-dev.1
  ngrouter: ^4.0.0-dev.1
  build: ^2.1.1
  build_config: ^1.0.0
  #mustache: ^1.0.0
  mustache_template: ^2.0.0
