name: angular_gallery
publish_to: none
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ngdart: ^7.0.1
  ngcomponents: ^1.0.0
  ngforms: ^4.0.0
  ngrouter: ^3.0.0
  build: ^2.1.1
  build_config: ^1.0.0
  mustache: ^1.0.0

dependency_overrides:
  ngcomponents:
    path: ../ngcomponents
