targets:
  $default:
    builders:
      ngcomponents|scss_builder:
        enabled: True
      angular_gallery|angular_gallery:
        enabled: False
      angular_gallery_section|angular_gallery_section:
        options:
          staticImageServer: "https://raw.githubusercontent.com"
