# See https://github.com/google/mono_repo.dart for details
sdk:
  - 2.17.0
  - stable
  - beta

stages:
  - build:
    - group:
      - command: dart pub run build_runner build web
      - command: dart pub run build_runner build web --release

cache:
  directories:
    - .dart_tool